# Generated by Django 4.1.4 on 2022-12-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aula", models.CharField(max_length=2)),
                ("hora_entrada", models.TimeField()),
            ],
        ),
        migrations.DeleteModel(name="Person",),
        migrations.AddField(
            model_name="profesor",
            name="idSalon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp1.salon"
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="idSalon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp1.salon"
            ),
        ),
        migrations.AddConstraint(
            model_name="profesor",
            constraint=models.UniqueConstraint(
                fields=("id", "first_name", "last_name"), name="primary_key_profesor"
            ),
        ),
        migrations.AddConstraint(
            model_name="alumno",
            constraint=models.UniqueConstraint(
                fields=("id", "first_name", "last_name"), name="primary_key_alumno"
            ),
        ),
    ]
